name = "Lumo Optimized"
author = "Luca"
version = "1.0.0"
description = "A performance-focused Fabric modpack with quality-of-life improvements, optimized rendering, and beautiful visuals."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3aa10e1dc2fb37baac3edc9bc66a4c26b0a97fe0f651ba73e775d1ee26de1da"

[versions]
fabric = "0.18.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7"]
