name = "Lumo Optimized"
author = "Luca"
version = "1.0.1"
description = "A performance-focused Fabric modpack with quality-of-life improvements, optimized rendering, and beautiful visuals."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6241e533dc1ea5d7a33a4349137da389eee2d879ff08fd412503a67efecca1c0"

[versions]
fabric = "0.18.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7"]
