name = "Lumo Optimized"
author = "Luca Silverentand"
version = "1.0.0"
description = "A performance-focused Fabric modpack for Minecraft 1.21.8 optimized for low-end devices, integrated graphics, and older hardware."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c6473862a42038730e82adff25c77894728df7aca99a6f22a91bf91349f4193"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7"]
